name: Create .env File

on:
  push:
    branches:
      - web

jobs:
  create-env:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ env.SUPABASE_SUPABASE_URL }}" > .env
          echo "SUPABASE_ANON_KEY=${{ env.SUPABASE_ANON_KEY }}" >> .env
          cat .env 
