name: Build and Deploy

on:
  push:
    branches:
      - web

jobs:
  create-env:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ vars.SUPABASE_URL }}" > .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          cat .env

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: node build.js